### ISSUE TITLE
[ BUG ] Missing library after Nvidia GPU driver installation using built-in app driver assistant

### ISSUE THREAD

**Issue by jp851** [H3rz3n/davinci-helper#11]
bonjour, l intallation de Davinci Resolve  19 se passe bien, mais impossible d'ouvrir l'appli.
Mode de traitement GPU non pris en charge. Dans l'onglet préférences  de Davinci pas de sélection possible CUDA.
Cordialement.

**Comment by H3rz3n** [comment]
Have you tried to use the app function to check if your GPU is supported and if you are using the correct gpu drivers ? What's you hardware ?

**Comment by jp851** [comment]
OUI, tout semble ok,  la GPU est NDVIDIA geforce GTX1650 pilote version 560.35.03 . j'utilise CUDA avec BLENDER  reconnu sans problème.

**Comment by H3rz3n** [comment]
If you right click in the DaVinci Resolve icon, does it have an option like  "Launch using discrete graphics" ? If yes you need to launch it using this option everytime. If you don't have it, tell me all your hardware and software configs :

CPU
GPU
iGPU (integrated if present)
Desktop/Laptop
Fedora Version

**Comment by jp851** [comment]
après réinstallation, toujours le même problème . 
CPU product: AMD Ryzen 5 PRO 4650G with Radeon Graphics
GPU NVIDIA geforce GTX 1650
Gnome 
FEDORA 40
Davinci Resolve 19

**Comment by H3rz3n** [comment]
> après réinstallation, toujours le même problème . CPU product: AMD Ryzen 5 PRO 4650G with Radeon Graphics GPU NVIDIA geforce GTX 1650 Gnome FEDORA 40 Davinci Resolve 19

Thank you for reporting your issue ! 

Try to use the latest update of the app (is out from a few minutes, v2.0.7) and exec the GPU Driver assistant option. It should make your card work with DaVinci. You can update the programm with you preferred store or using the command line sudo dnf check-update --refresh and sudo dnf update . Let me know if this fixed the issue (^_^).

If this didn't work try to check if do you have an option like "Open it with discrete gpu"  when right clicking on the D.Resolve icon.

**Comment by jp851** [comment]
Je n ai pas d option "" ouvir avec un GPU discret ""  après mise à jour  du driver GPU j' ai le message suivant. 
A compatible Nvidia GPU was found : GEFORCE GTX 1650

The RPM Fusion repository had already been added to the system, there was no need to add it.

DEBUG : It was impossible to install the proprietary Nvidia GPU driver.
Check your network connection and try again or install it by yourself.

Dernière vérification de l’expiration des métadonnées effectuée il y a 1:47:21 le lun. 21 oct. 2024 21:35:26.
Le paquet akmod-nvidia-3:560.35.03-1.fc40.x86_64 est déjà installé.
Toutes les correspondances ont été filtrées par filtrage modulaire pour les arguments: xorg-x11-drv-nvidia-cuda

Merci, bonne nuit.
je reprendrai les investigations demain.

**Comment by H3rz3n** [comment]
I've analized your log. In your case, it seems like the akmod-nvidia package is already installed, but the modular system is blocking the xorg-x11-drv-nvidia-cuda package because it's part of a different module. 

You can try to remove the Nvidia driver using : 
- `sudo dnf remove -y akmod-nvidia`, 
- `sudo dnf remove -y xorg-x11-drv-nvidia-cuda`
- `sudo dnf remove -y xorg-x11-drv-nvidia-cuda-libs`

Then try again using the GPU driver assistant. I'm trying to replicate your case on my laptop that uses a RTX 3050 but I'm not getting your error and I have the same version of the Nvidia GPU driver.

**Comment by jp851** [comment]
j' ai supprimé les pilotes , je n"ai plus cuda sur ma machine mais l erreur subsiste.

A compatible Nvidia GPU was found : GEFORCE GTX 1650

The RPM Fusion repository had already been added to the system, there was no need to add it.

DEBUG : It was impossible to install the proprietary Nvidia GPU driver.
Check your network connection and try again or install it by yourself.

Dernière vérification de l’expiration des métadonnées effectuée il y a 0:04:58 le mar. 22 oct. 2024 09:21:09.
Toutes les correspondances ont été filtrées par filtrage modulaire pour les arguments: xorg-x11-drv-nvidia-cuda


Please open an issue report and paste this error code on the project Git

**Comment by H3rz3n** [comment]
Can you please send the output of `sudo dnf module list` if there is any ?

**Comment by jp851** [comment]
Dernière vérification de l’expiration des métadonnées effectuée il y a 0:21:25 le mar. 22 oct. 2024 09:21:09.
cuda-fedora39-12-6-local
Name          Stream        Profiles               Summary                      
nvidia-driver latest-dkms   default [d], fm, ks    Nvidia driver for latest-dkms
                                                    branch                      
nvidia-driver open-dkms [d] default [d], fm, ks, s Nvidia driver for open-dkms b
                            rc                     ranch                        
nvidia-driver 560-dkms      default [d], fm, ks    Nvidia driver for 560-dkms br
                                                   anch                         
nvidia-driver 560-open      default [d], fm, ks, s Nvidia driver for 560-open br
                            rc                     anch                         

dnf list installed | grep cuda-fedora:

**Comment by jp851** [comment]
cuda-cccl-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-command-line-tools-12-6.x86_64                  12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-compiler-12-6.x86_64                            12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-crt-12-6.x86_64                                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cudart-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cudart-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cuobjdump-12-6.x86_64                           12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cupti-12-6.x86_64                               12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-cuxxfilt-12-6.x86_64                            12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-documentation-12-6.x86_64                       12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-driver-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-gdb-12-6.x86_64                                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-libraries-12-6.x86_64                           12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-libraries-devel-12-6.x86_64                     12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nsight-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nsight-compute-12-6.x86_64                      12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nsight-systems-12-6.x86_64                      12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nvcc-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvdisasm-12-6.x86_64                            12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvml-devel-12-6.x86_64                          12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvprof-12-6.x86_64                              12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-nvprune-12-6.x86_64                             12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvrtc-12-6.x86_64                               12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvrtc-devel-12-6.x86_64                         12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvtx-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvvm-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvvp-12-6.x86_64                                12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-opencl-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-opencl-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-profiler-api-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-sanitizer-12-6.x86_64                           12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-12-6.x86_64                             12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-toolkit-12-6-config-common.noarch               12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-12-config-common.noarch                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-config-common.noarch                    12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-tools-12-6.x86_64                               12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-visual-tools-12-6.x86_64                        12.6.2-1                            @cuda-fedora39-12-6-local                            
gds-tools-12-6.x86_64                                1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcublas-12-6.x86_64                                12.6.3.3-1                          @cuda-fedora39-12-6-local                            
libcublas-devel-12-6.x86_64                          12.6.3.3-1                          @cuda-fedora39-12-6-local                            
libcufft-12-6.x86_64                                 11.3.0.4-1                          @cuda-fedora39-12-6-local                            
libcufft-devel-12-6.x86_64                           11.3.0.4-1                          @cuda-fedora39-12-6-local                            
libcufile-12-6.x86_64                                1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcufile-devel-12-6.x86_64                          1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcurand-12-6.x86_64                                10.3.7.77-1                         @cuda-fedora39-12-6-local                            
libcurand-devel-12-6.x86_64                          10.3.7.77-1                         @cuda-fedora39-12-6-local                            
libcusolver-12-6.x86_64                              11.7.1.2-1                          @cuda-fedora39-12-6-local                            
libcusolver-devel-12-6.x86_64                        11.7.1.2-1                          @cuda-fedora39-12-6-local                            
libcusparse-12-6.x86_64                              12.5.4.2-1                          @cuda-fedora39-12-6-local                            
libcusparse-devel-12-6.x86_64                        12.5.4.2-1                          @cuda-fedora39-12-6-local                            
libnpp-12-6.x86_64                                   12.3.1.54-1                         @cuda-fedora39-12-6-local                            
libnpp-devel-12-6.x86_64                             12.3.1.54-1                         @cuda-fedora39-12-6-local                            
libnvfatbin-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvfatbin-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjitlink-12-6.x86_64                             12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjitlink-devel-12-6.x86_64                       12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjpeg-12-6.x86_64                                12.3.3.54-1                         @cuda-fedora39-12-6-local                            
libnvjpeg-devel-12-6.x86_64                          12.3.3.54-1                         @cuda-fedora39-12-6-local                            
nsight-compute-2024.3.2.x86_64                       2024.3.2.3-1                        @cuda-fedora39-12-6-local                            
nsight-systems-2024.5.1.x86_64                       2024.5.1.113_245134619542v0-0       @cuda-fedora39-12-6-local

**Comment by jp851** [comment]
dnf list installed | grep nvidia:
jp@Host-001:~$ dnf list installed | grep cuda-fedora
cuda-cccl-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-command-line-tools-12-6.x86_64                  12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-compiler-12-6.x86_64                            12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-crt-12-6.x86_64                                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cudart-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cudart-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cuobjdump-12-6.x86_64                           12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-cupti-12-6.x86_64                               12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-cuxxfilt-12-6.x86_64                            12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-documentation-12-6.x86_64                       12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-driver-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-gdb-12-6.x86_64                                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-libraries-12-6.x86_64                           12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-libraries-devel-12-6.x86_64                     12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nsight-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nsight-compute-12-6.x86_64                      12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nsight-systems-12-6.x86_64                      12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-nvcc-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvdisasm-12-6.x86_64                            12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvml-devel-12-6.x86_64                          12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvprof-12-6.x86_64                              12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-nvprune-12-6.x86_64                             12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvrtc-12-6.x86_64                               12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvrtc-devel-12-6.x86_64                         12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvtx-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvvm-12-6.x86_64                                12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-nvvp-12-6.x86_64                                12.6.80-1                           @cuda-fedora39-12-6-local                            
cuda-opencl-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-opencl-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-profiler-api-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-sanitizer-12-6.x86_64                           12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-12-6.x86_64                             12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-toolkit-12-6-config-common.noarch               12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-12-config-common.noarch                 12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-toolkit-config-common.noarch                    12.6.77-1                           @cuda-fedora39-12-6-local                            
cuda-tools-12-6.x86_64                               12.6.2-1                            @cuda-fedora39-12-6-local                            
cuda-visual-tools-12-6.x86_64                        12.6.2-1                            @cuda-fedora39-12-6-local                            
gds-tools-12-6.x86_64                                1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcublas-12-6.x86_64                                12.6.3.3-1                          @cuda-fedora39-12-6-local                            
libcublas-devel-12-6.x86_64                          12.6.3.3-1                          @cuda-fedora39-12-6-local                            
libcufft-12-6.x86_64                                 11.3.0.4-1                          @cuda-fedora39-12-6-local                            
libcufft-devel-12-6.x86_64                           11.3.0.4-1                          @cuda-fedora39-12-6-local                            
libcufile-12-6.x86_64                                1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcufile-devel-12-6.x86_64                          1.11.1.6-1                          @cuda-fedora39-12-6-local                            
libcurand-12-6.x86_64                                10.3.7.77-1                         @cuda-fedora39-12-6-local                            
libcurand-devel-12-6.x86_64                          10.3.7.77-1                         @cuda-fedora39-12-6-local                            
libcusolver-12-6.x86_64                              11.7.1.2-1                          @cuda-fedora39-12-6-local                            
libcusolver-devel-12-6.x86_64                        11.7.1.2-1                          @cuda-fedora39-12-6-local                            
libcusparse-12-6.x86_64                              12.5.4.2-1                          @cuda-fedora39-12-6-local                            
libcusparse-devel-12-6.x86_64                        12.5.4.2-1                          @cuda-fedora39-12-6-local                            
libnpp-12-6.x86_64                                   12.3.1.54-1                         @cuda-fedora39-12-6-local                            
libnpp-devel-12-6.x86_64                             12.3.1.54-1                         @cuda-fedora39-12-6-local                            
libnvfatbin-12-6.x86_64                              12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvfatbin-devel-12-6.x86_64                        12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjitlink-12-6.x86_64                             12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjitlink-devel-12-6.x86_64                       12.6.77-1                           @cuda-fedora39-12-6-local                            
libnvjpeg-12-6.x86_64                                12.3.3.54-1                         @cuda-fedora39-12-6-local                            
libnvjpeg-devel-12-6.x86_64                          12.3.3.54-1                         @cuda-fedora39-12-6-local                            
nsight-compute-2024.3.2.x86_64                       2024.3.2.3-1                        @cuda-fedora39-12-6-local                            
nsight-systems-2024.5.1.x86_64                       2024.5.1.113_245134619542v0-0       @cuda-fedora39-12-6-local                            
jp@Host-001:~$ dnf list installed | grep nvidia
kmod-nvidia-6.10.11-200.fc40.x86_64.x86_64           3:560.35.03-1.fc40                  @@commandline                                        
kmod-nvidia-6.10.9-200.fc40.x86_64.x86_64            3:560.35.03-1.fc40                  @@commandline                                        
kmod-nvidia-6.11.3-200.fc40.x86_64.x86_64            3:560.35.03-1.fc40                  @@commandline                                        
nvidia-gpu-firmware.noarch                           20241017-1.fc40                     @updates                                             
nvidia-modprobe.x86_64                               3:560.35.03-1.fc40                  @rpmfusion-nonfree-updates                           
nvidia-settings.x86_64                               3:560.35.03-1.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia.x86_64                           3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-libs.x86_64                      3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-power.x86_64                     3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-xorg-libs.x86_64                 3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates

**Comment by jp851** [comment]
je ne sais pas pourquoi les lignes sortent barrées au collage.

**Comment by H3rz3n** [comment]
Those packages from cuda-fedora39 are causing the conflict and the modular filtering 

You must remove all packages installed from cuda-fedora39, which can be identified with `dnf list installed | grep cuda-fedora` then disable the module entry that they create with `sudo dnf module disable nvidia-driver` then disable the cuda-fedora39 repo with `sudo dnf config-manager --disable cuda-fedora39` 

This should solve your issues and will allow you to install correctly `xorg-x11-drv-nvidia` from cli or with DaVinci Helper.

**Comment by jp851** [comment]
pouvvez vous me dire svp comment procéder pour supprimer les paquets cuda fedora 39.  je ne suis pas un grand connaisseur des commandes linux

**Comment by H3rz3n** [comment]
Probably should be enough use `sudo dnf remove cuda-fedora39`

**Comment by jp851** [comment]
Aucune correspondance pour le paramètre: cuda-fedora39
Aucun paquet marqué pour suppression.
Dépendances résolues.
Rien à faire.
Terminé !

**Comment by H3rz3n** [comment]
Then try to remove manually the packages until there a no more with the tag `@cuda-fedora-39`  when you check the installed packages with `sudo dnf list installed | grep cuda-fedora` :
`sudo dnf remove cuda-cccl cuda-command-line-tools cuda-compiler cuda-crt cuda-cudart cuda-cudart-devel cuda-cuobjdump cuda-cupti cuda-cuxxfilt cuda-documentation  cuda-driver-devel cuda-gdb cuda-libraries cuda-libraries-devel`

**Comment by jp851** [comment]
ça n" a pas fonctionné , mais j' ai repris votre commande avec les infos du tag . en fait le premier élimine presque la totalité. donc il n ' y a plus de paquet 39. par contre la commande sudo dnf module disable nvidia-driver ne fonctionne pas . quand au dépot je l'ai fermé depuis LOGICIELS.

**Comment by jp851** [comment]
Impossible de résoudre le paramètre nvidia-driver
Erreur : Problèmes dans la requête :
groupes ou modules manquants : nvidia-driver

**Comment by H3rz3n** [comment]
Perfect, now tell me the output of the following commands :

- `dnf list installed | grep cuda`
- `dnf list installed | grep nvidia`

**Comment by jp851** [comment]
jp@Host-001:~$ dnf list installed | grep cuda
cuda-repo-fedora39-12-6-local.x86_64                 12.6.2_560.35.03-1                  @System

**Comment by jp851** [comment]
p@Host-001:~$ dnf list installed | grep cuda
cuda-repo-fedora39-12-6-local.x86_64                 12.6.2_560.35.03-1                  @System                                              
jp@Host-001:~$ dnf list installed | grep nvidia
kmod-nvidia-6.10.11-200.fc40.x86_64.x86_64           3:560.35.03-1.fc40                  @@commandline                                        
kmod-nvidia-6.10.9-200.fc40.x86_64.x86_64            3:560.35.03-1.fc40                  @@commandline                                        
kmod-nvidia-6.11.3-200.fc40.x86_64.x86_64            3:560.35.03-1.fc40                  @@commandline                                        
nvidia-gpu-firmware.noarch                           20241017-1.fc40                     @updates                                             
nvidia-modprobe.x86_64                               3:560.35.03-1.fc40                  @rpmfusion-nonfree-updates                           
nvidia-settings.x86_64                               3:560.35.03-1.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia.x86_64                           3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-libs.x86_64                      3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-power.x86_64                     3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates                           
xorg-x11-drv-nvidia-xorg-libs.x86_64                 3:560.35.03-5.fc40                  @rpmfusion-nonfree-updates

**Comment by H3rz3n** [comment]
Now try to remove `cuda-repo-fedora39-12-6-local.x86_64 12.6.2_560.35.03-1` with :

`sudo dnf remove cuda-repo-fedora39-12-6-local.x86_64 12.6.2_560.35.03-1`

**Comment by jp851** [comment]
voilà c est OK

**Comment by jp851** [comment]
jp@Host-001:~$ dnf repolist
id du dépôt                                          nom du dépôt
copr:copr.fedorainfracloud.org:adriend:fedora-apps   Copr repo for fedora-apps owned by adriend
copr:copr.fedorainfracloud.org:herzen:davinci-helper Copr repo for davinci-helper owned by herzen
copr:copr.fedorainfracloud.org:phracek:PyCharm       Copr repo for PyCharm owned by phracek
fedora                                               Fedora 40 - x86_64
fedora-cisco-openh264                                Fedora 40 openh264 (From Cisco) - x86_64
google-chrome                                        google-chrome
rpmfusion-free                                       RPM Fusion for Fedora 40 - Free
rpmfusion-free-tainted                               RPM Fusion for Fedora 40 - Free tainted
rpmfusion-free-updates                               RPM Fusion for Fedora 40 - Free - Updates
rpmfusion-nonfree                                    RPM Fusion for Fedora 40 - Nonfree
rpmfusion-nonfree-nvidia-driver                      RPM Fusion for Fedora 40 - Nonfree - NVIDIA Driver
rpmfusion-nonfree-steam                              RPM Fusion for Fedora 40 - Nonfree - Steam
rpmfusion-nonfree-tainted                            RPM Fusion for Fedora 40 - Nonfree tainted
rpmfusion-nonfree-updates                            RPM Fusion for Fedora 40 - Nonfree - Updates
updates                                              Fedora 40 - x86_64 - Updates
vivaldi                                              vivaldi

**Comment by H3rz3n** [comment]
Perfect, now you should be able to install `xorg-x11-drv-nvidia-cuda` with `sudo dnf install xorg-x11-drv-nvidia-cuda` without any errors

**Comment by H3rz3n** [comment]
Yes, or you can use agan the gpu driver assistant in DaVinci Helper, it's the same.

**Comment by H3rz3n** [comment]
It's was a pleasure to help you. Thank you for using DaVinci Helper ! Stay in touch for new updates ! (^_^)

**Comment by H3rz3n** [comment]
It's was a pleasure to help you. Thank you for using DaVinci Helper ! Stay in touch for new updates ! (^_^)

**Comment by jp851** [comment]
Pas de problème. c'est tout de même une perle DaVinci Helper. Il n 'est pas assez connu, beaucoup de gens galèrent pour installer Davinci Resolve sur linux. je suis tombé dessus après des multiples recherches.
encore bravo.

**Comment by H3rz3n** [comment]
Thank you so much, your compliment is very appreciated (^_^)
