### ISSUE TITLE
[BUG] Error during the installation of FFMPEG using built-in function

### ISSUE THREAD

**Issue by Erebosus** [H3rz3n/davinci-helper#14]
Hi! I'm experiencing an issue with davinci-helper on Fedora 41. Although FFmpeg is installed and the RPM Fusion repository is correctly enabled, davinci-helper doesn’t seem to recognize FFmpeg and shows the following error:

"Install FFmpeg to use this feature"

Issue Details:

Fedora Version: 41
davinci-helper Version: latest version from the Copr repository herzen/davinci-helper
FFmpeg is installed and accessible at /usr/bin/ffmpeg
Running ffmpeg -version works fine and displays the installed version.
Steps I’ve Tried:

Verified the presence of FFmpeg on the system (/usr/bin/ffmpeg).
Reinstalled FFmpeg via RPM Fusion and tried manual installation.
Ran davinci-helper with superuser permissions.
![Screenshot From 2024-11-05 23-12-22](https://github.com/user-attachments/assets/5c65e9ff-6db8-417e-9fc8-08ff21a0b6cd)

Enabled the Copr repository herzen/davinci-helper and installed davinci-helper from there.
Despite these steps, the error persists.

Detailed Error Message:

vbnet
Copia codice
Error: "Install FFmpeg to use this feature"
DEBUG: Failed to install FFMPEG from RPM Fusion

**Comment by H3rz3n** [comment]
I've updated DaVinci Helper fixing a bug that prevented the RPM-Fusion repository from installing properly. Probably the issue was caused by that. Let me know if this work (^_^).

**Comment by Erebosus** [comment]
> Ho aggiornato DaVinci Helper risolvendo un bug che ha impedito l'installazione corretta del repository RPM-Fusion. Probabilmente il problema è stato causato da quello. Fammi sapere se funziona (^ _ ^).

Good day, I updated the software, I haven't tried it yet but I can tell you that it doesn't give me the error anymore
![Screenshot From 2024-11-08 00-59-58](https://github.com/user-attachments/assets/6a864653-7e37-4c4e-993a-8adde9fbedd6)
