### ISSUE TITLE
[BUG] Error during the conversion of .mp4 video file with built-in video converter

### ISSUE THREAD

**Issue by F0XSN4P** [H3rz3n/davinci-helper#17]
Hello, I have encountered an annoying problem. Every time I have to convert a .mp4 file to mov, it says to wait but does not give me any results. The first time I tried it worked

**Comment by H3rz3n** [comment]
Probably there is some sort of problem with your clip. Can you please try to launch DaVinci Helper from the terminal using `davinci-helper`, try to convert the video and see if there is an output in the terminal with more information about the error ?

Can you please provide me sample of the clip do make me easier find what is causing the bug ? 
I'm sorry for the delay in responding, thank you for using DaVinci Helper !
