### ISSUE TITLE
Request | Publish to copr

### ISSUE THREAD

**Issue by Malix-Labs** [H3rz3n/davinci-helper#2]
https://copr.fedorainfracloud.org/

**Comment by H3rz3n** [comment]
Thank you, I didn't know that it exist. I will check it out soon. Currently I'm finishing the v2.0.0 with a brand new UI in full Adwaita and with an integration with simple UI for FFMPEG to easily convert media for DaVinci Resolve.

**Comment by Malix-Labs** [comment]
Nice to know!

**Comment by Malix-Labs** [comment]
https://copr.fedorainfracloud.org/coprs/herzen/davinci-helper/
