### ISSUE TITLE
[ENHANCEMENT] Add support for AMD iGPU 880/890M

### ISSUE THREAD

**Issue by Chevek** [H3rz3n/davinci-helper#21]
Davinci-helper does not find my GPU. I'm on a new laptop (ASUS Zenbook S 16, with the new AMD CPU AI with integrated GPU.

Mine is 880M, I bet the situation is the same with 890M.
For reference: https://en.wikipedia.org/wiki/List_of_AMD_Ryzen_processors#Ryzen_AI_300_series

Your test wont find it : https://github.com/H3rz3n/davinci-helper/blob/9fcce5e44112b60cf20f79d179a47a98535ef655/davinci-helper/davinci_helper/functions/logic/function_4.py#L51C5-L51C99

With "display" you will get it :
```
chevek@fedora:~$ lspci | grep -i vga
chevek@fedora:~$ lspci | grep -i display
c4:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Strix [Radeon 880M / 890M] (rev c4)
```
I join the full lspci output.
[lspci.txt](https://github.com/user-attachments/files/17893081/lspci.txt)

Benchmark test within Blackmagic RAW speed test
![Capture d’écran du 2024-11-24 12-32-24](https://github.com/user-attachments/assets/c3e07a74-9b13-4624-a4cd-a1617fa5660b)

The GPU is usable inside Davinci Resolve:
![Capture d’écran du 2024-11-24 13-04-43](https://github.com/user-attachments/assets/de33161d-ec3e-40cb-896e-4bf164504f9e)

Regards

**Comment by H3rz3n** [comment]
Thank you for telling it to me, I didn't know that those integrated GPU work with DaVinci Resolve on Linux. I will add them to the support list. Thank you using DaVinci Helper (^_^)

**Comment by H3rz3n** [comment]
I added the support for your GPU in the new release of DaVinci Helper. Please let me know if this correctly works for your GPU ! Thank for using and supporting DaVinci Helper ! (^_^)

**Comment by Chevek** [comment]
Tested 2.2.0. It could not find my GPU.

This test does not work on my system:
`gpu_lspci = subprocess.run("lspci | grep -i vga", shell=True, capture_output=True, text=True )`
There is no "vga" string in the lspci output.
In my output, the line with the GPU is:
`c4:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Strix [Radeon 880M / 890M] (rev c4)`

May I suggest this change:
`gpu_lspci = subprocess.run("lspci | grep -Ei 'vga|display'", shell=True, capture_output=True, text=True )`
(I'm not sure about the single quotes...)

**Comment by H3rz3n** [comment]
> Tested 2.2.0. It could not find my GPU.
> 
> This test does not work on my system:
> `gpu_lspci = subprocess.run("lspci | grep -i vga", shell=True, capture_output=True, text=True )`
> There is no "vga" string in the lspci output.
> In my output, the line with the GPU is:
> `c4:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Strix [Radeon 880M / 890M] (rev c4)`
> 
> May I suggest this change:
> `gpu_lspci = subprocess.run("lspci | grep -Ei 'vga|display'", shell=True, capture_output=True, text=True )`
> (I'm not sure about the single quotes...)

Thank you for your feedback, I will make a fix in the tomorrow morning (EU-Rome time). (^_^)

**Comment by H3rz3n** [comment]
I update the package with the line you suggested, I will put your name in the credits of this release. Let me know if know works properly (^_^)
