### ISSUE TITLE
Issue- There was an error reading what version of Fedora is installed

### ISSUE THREAD

**Issue by zlcpoker** [H3rz3n/davinci-helper#8]
Hello,
Please help, At the first step - Install missing dependencies, I got this error message. I'm on Nobara 40, Nvidia edition.
_"DEBUG : There was an error reading what version of Fedora is installed :

cat: /etc/fedora-release: No such file or directory"_

Thank you

**Comment by H3rz3n** [comment]
Hi, thank you for using DaVinci Helper. The error that you are getting is due to a misconfiguration in the DaVinci Helper OS checking function. I will solve it in few hours. Thank you for asking help and to contribute to the improvement of DaVinci Helper 😄

**Comment by H3rz3n** [comment]
The bug has been solved, now it should work correctly on Nobara 40 😄
